# - name: check if kubeconfig already exists
#   stat:
#     path: ~/.kube/config-{{ k3s.kubeconfig_context }}
#   register: kubeconfig_target
#   delegate_to: localhost

- name: Copy k3s kubeconfig file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config-{{ k3s.kubeconfig_context }}
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: 0600
  # when: not kubeconfig_target.stat.exists

- name: Replace server
  command: >-
    k3s kubectl config set-cluster default --server=https://{{ k3s.kubeconfig_server }}
      --kubeconfig ~{{ ansible_user }}/.kube/config-{{ k3s.kubeconfig_context }}
  changed_when: False
  # when: not kubeconfig_target.stat.exists

- name: Replace context
  command: >-
    k3s kubectl config rename-context default {{ k3s.kubeconfig_context }}
      --kubeconfig ~{{ ansible_user }}/.kube/config-{{ k3s.kubeconfig_context }}
  changed_when: False
  # when: not kubeconfig_target.stat.exists

- name: Download kubeconfig to local machine
  fetch:
    src: ~{{ ansible_user }}/.kube/config-{{ k3s.kubeconfig_context }}
    dest: ~/.kube/config-{{ k3s.kubeconfig_context }}
    flat: yes
  # when: not kubeconfig_target.stat.exists