---
- name: Stop current k3s service
  ansible.builtin.shell:
    cmd: |
      /usr/local/bin/k3s-killall.sh
  ignore_errors: true

- name: Remove current k3s installation
  ansible.builtin.shell:
    cmd: |
      /usr/local/bin/k3s-agent-uninstall.sh
  ignore_errors: true

- name: Remove rancher directory
  ansible.builtin.file:
    path: /var/lib/rancher
    state: absent

- name: Download k3s script installer
  get_url:
    url: "https://get.k3s.io"
    dest: /tmp/k3s-installer.sh
    mode: '755'

- name: Install k3s
  shell: |
    cat /tmp/k3s-installer.sh | \
    INSTALL_K3S_VERSION={{k3s.release_version}} \
    K3S_URL=https://{{k3s.kubeconfig_server}} \
    K3S_TOKEN={{k3s.node_token}} \
    sh -

- name: Ensure k3s service is running
  ansible.builtin.service:
    name: k3s-agent
    enabled: yes
    state: started    
